name: rencanapa
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.0-74.0.dev

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0 
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0 
  video_player: ^2.8.6
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.1 # <--- DEPENDENSI BARU

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/success_video.mp4 
