// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf2JO4ezCjJoYSuoBHXyFzpRixv_h28qA',
    appId: '1:220576630337:web:3c94e86dcc51f13f6728c0',
    messagingSenderId: '220576630337',
    projectId: 'rencanapa-b0d44',
    authDomain: 'rencanapa-b0d44.firebaseapp.com',
    storageBucket: 'rencanapa-b0d44.firebasestorage.app',
    measurementId: 'G-LVLZ8LDT7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCQBjChRqzzTqlI1qqeQdQDGQh8m_mUnc',
    appId: '1:220576630337:android:d37bf5d4e9edbb976728c0',
    messagingSenderId: '220576630337',
    projectId: 'rencanapa-b0d44',
    storageBucket: 'rencanapa-b0d44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk_q13khif6Bhig-pUi34AEluR1ap8ZT8',
    appId: '1:220576630337:ios:05033e3f115d08e26728c0',
    messagingSenderId: '220576630337',
    projectId: 'rencanapa-b0d44',
    storageBucket: 'rencanapa-b0d44.firebasestorage.app',
    iosBundleId: 'com.example.rencanapa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk_q13khif6Bhig-pUi34AEluR1ap8ZT8',
    appId: '1:220576630337:ios:05033e3f115d08e26728c0',
    messagingSenderId: '220576630337',
    projectId: 'rencanapa-b0d44',
    storageBucket: 'rencanapa-b0d44.firebasestorage.app',
    iosBundleId: 'com.example.rencanapa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf2JO4ezCjJoYSuoBHXyFzpRixv_h28qA',
    appId: '1:220576630337:web:880a25161f7738956728c0',
    messagingSenderId: '220576630337',
    projectId: 'rencanapa-b0d44',
    authDomain: 'rencanapa-b0d44.firebaseapp.com',
    storageBucket: 'rencanapa-b0d44.firebasestorage.app',
    measurementId: 'G-D6TR0HPHXX',
  );
}
